### ISSUE TITLE
Search brings back XML raw data

### ISSUE THREAD

**Issue by Tzvook** [lokothodida/gs-catalog#9]
search gives XML data with no link to the product ... something like that:

object(I18nSearchCatalogResultItem)#111 (8) { ["data":protected]=> object(CatalogProduct)#3 (5) { ["product":"CatalogProduct":private]=> object(SimpleXMLElement)#115 (8) { ["title"]=> object(SimpleXMLElement)#112 (0) { } ["categories"]=> object(SimpleXMLElement)#77 (1) { ["category"]=> array(4) { [0]=> string(17) "0-ktgvryh-rashvnh" [1]=> string(15) "1-ktgvryh-shnyh" [2]=> string(16) "3-ktgvryh-rbyayt" [3]=> string(19) "4-tt-ktgvryh-rbyayt" } } ["instock"]=> object(SimpleXMLElement)#123 (0) { } ["price"]=> object(SimpleXMLElement)#119 (0) { } ["image"]=> object(SimpleXMLElement)#116 (0) { } ["rating"]=> object(SimpleXMLElement)#124 (0) { } ["description"]=> object(SimpleXMLElement)#125 (0) { } ["id"]=> string(13) "0-mvtzr-rashv" } ["categories":"CatalogProduct":private]=> array(0) { } ["file":"CatalogProduct":private]=> NULL ["url":"CatalogProduct":private]=> NULL ["slugged":"CatalogProduct":private]=> NULL } ["categories":protected]=> bool(false) ["product":protected]=> bool(false) ["id":"I18nSearchResultItem":private]=> string(17) "cat:0-mvtzr-rashv" ["language":"I18nSearchResultItem":private]=> string(2) "he" ["creDate":"I18nSearchResultItem":private]=> int(1409389197) ["pubDate":"I18nSearchResultItem":private]=> int(1409389197) ["score":"I18nSearchResultItem":private]=> int(1) }

**Comment by lokothodida** [comment]
To my knowledge, the search hasn't fully been integrated, so it's no surprise that it isn't working as desired.

Can you [elaborate](https://github.com/lokothodida/gs-catalog/wiki/Opening%20issues) on how you are using it at the moment?

**Comment by Tzvook** [comment]
I used the site's search ( Gs ) with a term from a product description..

**Comment by lokothodida** [comment]
I see where the problem is. I can hack out a quick solution (and partially have on the v0.3 branch), but I seriously need to restructure the way that the various classes interact with each other, because they are quickly becoming unwieldy.

The search is quick to fix, but providing the correct links will be a bit difficult.

**Comment by lokothodida** [comment]
Searching is implemented (#14).
